// client/imposteur-words.js - Pairs and words dataset for SousLaCouverture (Imposteur)
(function(window) {
  const IMPOSTEUR_WORDS = {
    general: [
      { civil: 'Café', impostor: 'Thé' },
      { civil: 'Chien', impostor: 'Chat' },
      { civil: 'Lion', impostor: 'Tigre' },
      { civil: 'Dauphin', impostor: 'Baleine' },
      { civil: 'Pizza', impostor: 'Burger' },
      { civil: 'Avion', impostor: 'Train' },
      { civil: 'Lune', impostor: 'Soleil' },
      { civil: 'Chocolat', impostor: 'Vanille' },
      { civil: 'Mer', impostor: 'Piscine' },
      { civil: 'Guitare', impostor: 'Piano' },
      { civil: 'Orage', impostor: 'Pluie' },
      { civil: 'Vélo', impostor: 'Trottinette' },
      { civil: 'Paris', impostor: 'Londres' },
      { civil: 'Mer', impostor: 'Océan' },
      { civil: 'Pluie', impostor: 'Neige' },
      { civil: 'Orage', impostor: 'Tempête' },
      { civil: 'Moto', impostor: 'Scooter' },
      { civil: 'Fraise', impostor: 'Framboise' },
      { civil: 'Pomme', impostor: 'Poire' },
      { civil: 'Pain', impostor: 'Croissant' },
      { civil: 'Beurre', impostor: 'Margarine' },
      { civil: 'Sel', impostor: 'Poivre' },
      { civil: 'Or', impostor: 'Argent' },
      { civil: 'Diamant', impostor: 'Rubis' },
      { civil: 'Livre', impostor: 'Liseuse' },
      { civil: 'Stylo', impostor: 'Crayon' },
      { civil: 'Chapeau', impostor: 'Casquette' },
      { civil: 'Chaussures', impostor: 'Chaussettes' },
      { civil: 'Lunettes', impostor: 'Lentilles' },
      { civil: 'Cinéma', impostor: 'Théâtre' },
      { civil: 'Télévision', impostor: 'Projecteur' },
      { civil: 'Coca-Cola', impostor: 'Pepsi' },
      { civil: 'Glace', impostor: 'Sorbet' },
      { civil: 'Savon', impostor: 'Shampoing' },
      { civil: 'Bateau', impostor: 'Sous-marin' },
      { civil: 'Montagne', impostor: 'Volcan' },
      { civil: 'Éléphant', impostor: 'Rhinocéros' },
      { civil: 'Pâtes', impostor: 'Riz' },
      { civil: 'Bière', impostor: 'Vin' },
      { civil: 'Chausson', impostor: 'Pantoufle' }
    ],
    anime: [
      { civil: 'Son Goku', impostor: 'Végéta' },
      { civil: 'Son Gohan', impostor: 'Trunks' },
      { civil: 'Piccolo', impostor: 'Kamé Sennin' },
      { civil: 'Freezer', impostor: 'Cell' },
      { civil: 'Krilin', impostor: 'Yamcha' },
      { civil: 'Majin Bou', impostor: 'Kid Bou' },
      { civil: 'Bardock', impostor: 'Broly' },
      { civil: 'Naruto Uzumaki', impostor: 'Sasuke Uchiha' },
      { civil: 'Kakashi Hatake', impostor: 'Obito Uchiha' },
      { civil: 'Itachi Uchiha', impostor: 'Sasuke Uchiha' },
      { civil: 'Jiraiya', impostor: 'Orochimaru' },
      { civil: 'Gaara', impostor: 'Kankurô' },
      { civil: 'Minato Namikaze', impostor: 'Tobirama Senju' },
      { civil: 'Hinata Hyûga', impostor: 'Sakura Haruno' },
      { civil: 'Shikamaru Nara', impostor: 'Chôji Akimichi' },
      { civil: 'Monkey D. Luffy', impostor: 'Roronoa Zoro' },
      { civil: 'Sanji Vinsmoke', impostor: 'Roronoa Zoro' },
      { civil: 'Portgas D. Ace', impostor: 'Sabo' },
      { civil: 'Shanks le Roux', impostor: 'Dracule Mihawk' },
      { civil: 'Nami', impostor: 'Nico Robin' },
      { civil: 'Tony-Tony Chopper', impostor: 'Usopp' },
      { civil: 'Brook', impostor: 'Franky' },
      { civil: 'Kaido', impostor: 'Big Mom' },
      { civil: 'Gold Roger', impostor: 'Barbe Blanche' },
      { civil: 'Light Yagami', impostor: 'L (Ryuzaki)' },
      { civil: 'Near', impostor: 'Mello' },
      { civil: 'Gon Freecss', impostor: 'Killua Zoldyck' },
      { civil: 'Kurapika', impostor: 'Leorio Paradinight' },
      { civil: 'Hisoka Morow', impostor: 'Illumi Zoldyck' },
      { civil: 'Netero', impostor: 'Meruem' },
      { civil: 'Izuku Midoriya', impostor: 'Katsuki Bakugo' },
      { civil: 'Shoto Todoroki', impostor: 'Eijiro Kirishima' },
      { civil: 'All Might', impostor: 'Endeavor' },
      { civil: 'Yuji Itadori', impostor: 'Megumi Fushiguro' },
      { civil: 'Satoru Gojo', impostor: 'Suguru Geto' },
      { civil: 'Ryomen Sukuna', impostor: 'Mahito' },
      { civil: 'Tanjiro Kamado', impostor: 'Zenitsu Agatsuma' },
      { civil: 'Nezuko Kamado', impostor: 'Kanao Tsuyuri' },
      { civil: 'Kyojuro Rengoku', impostor: 'Giyu Tomioka' },
      { civil: 'Eren Jäger', impostor: 'Armin Arlert' },
      { civil: 'Levi Ackerman', impostor: 'Erwin Smith' },
      { civil: 'Mikasa Ackerman', impostor: 'Annie Leonhart' },
      { civil: 'Ichigo Kurosaki', impostor: 'Uryu Ishida' },
      { civil: 'Edward Elric', impostor: 'Alphonse Elric' },
      { civil: 'Denji', impostor: 'Aki Hayakawa' },
      { civil: 'Natsu Dragneel', impostor: 'Gray Fullbuster' },
      { civil: 'Saitama', impostor: 'Genos' },
      { civil: 'Ken Kaneki', impostor: 'Touka Kirishima' },
      { civil: 'Lelouch vi Britannia', impostor: 'Suzaku Kururugi' },
      { civil: 'Jotaro Kujo', impostor: 'Dio Brando' },
      { civil: 'Pikachu', impostor: 'Évoli' },
      { civil: 'Sacha Ketchum', impostor: 'Ondine' }
    ],
    jeux_video: [
      { civil: 'Mario', impostor: 'Luigi' },
      { civil: 'Zelda', impostor: 'Link' },
      { civil: 'Sonic', impostor: 'Shadow' },
      { civil: 'Kratos (God of War)', impostor: 'Master Chief (Halo)' },
      { civil: 'Joel (The Last of Us)', impostor: 'Ellie (The Last of Us)' },
      { civil: 'Lara Croft (Tomb Raider)', impostor: 'Nathan Drake (Uncharted)' },
      { civil: 'Sans (Undertale)', impostor: 'Papyrus (Undertale)' },
      { civil: 'Steve (Minecraft)', impostor: 'Alex (Minecraft)' },
      { civil: 'Sub-Zero (Mortal Kombat)', impostor: 'Scorpion (Mortal Kombat)' },
      { civil: 'Ryu (Street Fighter)', impostor: 'Ken Masters (Street Fighter)' },
      { civil: 'Geralt de Riv (The Witcher)', impostor: 'Arthur Morgan (RDR2)' },
      { civil: 'Crash Bandicoot', impostor: 'Spyro le Dragon' },
      { civil: 'Rayman', impostor: 'Lapin Crétin' },
      { civil: 'Doom Slayer (Doom)', impostor: 'Duke Nukem' },
      { civil: 'Bowser (Mario)', impostor: 'Donkey Kong' },
      { civil: 'Princesse Peach', impostor: 'Princesse Daisy' },
      { civil: 'Solid Snake (Metal Gear)', impostor: 'Sam Fisher (Splinter Cell)' },
      { civil: 'Ezio Auditore (Assassin\'s Creed)', impostor: 'Altaïr Ibn-La\'Ahad (Assassin\'s Creed)' },
      { civil: 'Trevor Philips (GTA V)', impostor: 'Michael De Santa (GTA V)' },
      { civil: 'Cloud Strife (Final Fantasy VII)', impostor: 'Sephiroth (Final Fantasy VII)' },
      { civil: 'Kirby', impostor: 'Meta Knight' },
      { civil: 'Tracer (Overwatch)', impostor: 'Widowmaker (Overwatch)' },
      { civil: 'Phoenix Wright (Ace Attorney)', impostor: 'Professeur Layton' },
      { civil: 'Cuphead', impostor: 'Mugman' },
      { civil: 'Jinx (League of Legends)', impostor: 'Vi (League of Legends)' },
      { civil: 'Glados (Portal)', impostor: 'Wheatley (Portal)' },
      { civil: 'Leon S. Kennedy (Resident Evil)', impostor: 'Chris Redfield (Resident Evil)' }
    ],
    films_series: [
      { civil: 'Harry Potter', impostor: 'Lord Voldemort' },
      { civil: 'Batman (Bruce Wayne)', impostor: 'Le Joker' },
      { civil: 'Jack Sparrow', impostor: 'Indiana Jones' },
      { civil: 'Shrek', impostor: 'Princesse Fiona' },
      { civil: 'Luke Skywalker', impostor: 'Darth Vador' },
      { civil: 'Walter White (Heisenberg)', impostor: 'Jesse Pinkman' },
      { civil: 'Sherlock Holmes', impostor: 'Docteur Watson' },
      { civil: 'Iron Man (Tony Stark)', impostor: 'Captain America (Steve Rogers)' },
      { civil: 'Gandalf (LGDF)', impostor: 'Albus Dumbledore (Harry Potter)' },
      { civil: 'Frodon Sacquet', impostor: 'Sam Gamegie' },
      { civil: 'Jon Snow', impostor: 'Daenerys Targaryen' },
      { civil: 'Neo (Matrix)', impostor: 'Morpheus (Matrix)' },
      { civil: 'Michael Scott', impostor: 'Dwight Schrute' },
      { civil: 'Rick Sanchez', impostor: 'Morty Smith' },
      { civil: 'Mercredi Addams', impostor: 'Eleven (Stranger Things)' },
      { civil: 'James Bond (007)', impostor: 'Ethan Hunt (Mission Impossible)' },
      { civil: 'Marty McFly', impostor: 'Doc Brown (Emmett Brown)' },
      { civil: 'Jack Dawson (Titanic)', impostor: 'Rose DeWitt Bukater' },
      { civil: 'Le Joker', impostor: 'Harley Quinn' },
      { civil: 'Thanos (Marvel)', impostor: 'Darth Vador (Star Wars)' },
      { civil: 'Thor (Marvel)', impostor: 'Loki (Marvel)' },
      { civil: 'Forrest Gump', impostor: 'Benjamin Button' },
      { civil: 'Dominic Toretto (Fast & Furious)', impostor: 'Brian O\'Conner (Fast & Furious)' },
      { civil: 'Barney Stinson (HIMYM)', impostor: 'Ted Mosby (HIMYM)' },
      { civil: 'Spider-Man (Peter Parker)', impostor: 'Batman (Bruce Wayne)' },
      { civil: 'Gollum', impostor: 'Bilbon Sacquet' },
      { civil: 'Thomas Shelby (Peaky Blinders)', impostor: 'Alfie Solomons (Peaky Blinders)' }
    ]
  };

  window.IMPOSTEUR_WORDS = IMPOSTEUR_WORDS;
})(typeof window !== 'undefined' ? window : this);
